services:
  - type: web
    name: rastreador-de-gastos-personal 
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run build
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: rastreador-gastos-db
    plan: free
    region: oregon
    databaseName: gastos_db_k2w7
    user: gastos_user
    ipAllowList: []
