services:
  - type: web
    name: rastreador-gastos
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true

  - type: pserv
    name: rastreador-gastos-db
    plan: free
    region: oregon
    databaseName: gastos_db_k2w7
    databaseUser: gastos_user
    ipAllowList: 
    - source: 0.0.0.0/0
      description: everywhere
    postgresMajorVersion: "16"
  version: "1"

envVarGroups:
  - name: app-settings
    envVars:
      - key: API_URL
        value: https://rastreador-gastos.onrender.com/api
      - key: DATABASE_URL
        fromDatabase:
          name: rastreador-gastos-db
          property: connectionString
